### ISSUE TITLE
Can't get script to work

### ISSUE THREAD

**Issue by AdminSB** [abelmartinromero/business_hours#1]
Hi Abel,

Thanks for this script, I think this does exactly what I was looking for. Unfortunately I have a problem getting it to work. I tried getting in touch with you through the Zendesk help centre, but they recommended contacting you directly.

I added all the required information (e.g., API key, greeting IDs) to the bh-config file and created a Windows batch file to execute the business-hours.php file, which I call every 30 mins. 

I see the file is running without errors and it is giving me the "Setting the voicemail for number ..." message. However, when I call our zendesk number I still get the "inside of business hours" voicemail.

See also the added screenshot of the commandline messages. As you can see I added some echo commands to the PHP to see what exactly was happening since I am not particularly skilled at PHP.

Hopefully you can help us out!

Rutger

**Comment by abmartinr** [comment]
Hi @AdminSB !

I'll have a look at it and retest it to see if I can find any issues with the script. On the meantime, I'd suggest that you update the screenshot to avoid showing your number publicly, in case you don't want to get spammed. 

I'll keep you posted here.

Cheers

**Comment by abmartinr** [comment]
Hey @AdminSB, I've created a new branch and added a few extra echoes so I can see what is going on while you run the script.

Could you please update your business_hours.php code and rerun the test. After you do so, please paste here the output of the terminal. Feel free to redact the phone numbers. :)

**Comment by AdminSB** [comment]
Hi Abel,

Thanks for the quick response! 
I just ran the modified script (with the redacted phone number :) ):

![screenshot](https://cloud.githubusercontent.com/assets/13415396/8831408/5e192950-30a2-11e5-8d0c-a99a9d949154.png)

**Comment by abmartinr** [comment]
I'm checking this in more depth since now I'm getting a weird error I didn't get before using the script. It's not working for my account either. I'll update as soon as I find out more.

**Comment by abmartinr** [comment]
Hey @AdminSB . I've fixed the issues and improved the logic of the script. I've also added more logs.

Can you please test it out? IT can be found here: https://github.com/abmartinr/Business-Hours-Voicemail-Greetings/blob/extra_debug_shell/business_hours.php

**Comment by AdminSB** [comment]
Hi Abel, 

That seems to have done it! Both the day > night as well as the night > day transitions are working flawlessly now. Thank you so much for your help, this is going to be a real time saver!

Rutger
